# Generated by Django 2.2.4 on 2019-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0004_evidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='folio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
