# Generated by Django 2.2.1 on 2019-09-17 03:21

import apps.direccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0005_actividades_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='evidencias',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=apps.direccion.models.act_directory_path),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='permisos',
            field=models.ManyToManyField(related_name='permisos', to='direccion.PermisosUser'),
        ),
    ]
