# Generated by Django 2.2.1 on 2019-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0006_auto_20190916_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermisosUser',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='permisos',
            field=models.ManyToManyField(related_name='permisos', to='direccion.Permisos'),
        ),
    ]
