# Generated by Django 2.2.4 on 2019-09-17 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0007_auto_20190916_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='permisos',
        ),
        migrations.AddField(
            model_name='permisos',
            name='assign_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisos',
            name='delete_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisos',
            name='edit_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisos',
            name='see_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL),
        ),
    ]
