# Generated by Django 2.2.4 on 2019-09-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0009_auto_20190917_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='delete_all',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='edit_all',
        ),
    ]
