# Generated by Django 2.2.4 on 2019-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0011_auto_20190919_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='see_in_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='see_in_select',
            field=models.BooleanField(default=True),
        ),
    ]
