# Generated by Django 2.2.4 on 2019-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0012_auto_20190919_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
