# Generated by Django 2.2.4 on 2019-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0013_direcciones_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
