# Generated by Django 2.2.4 on 2019-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0014_auto_20190930_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
