# Generated by Django 2.2.4 on 2019-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0015_auto_20190930_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='comentarios',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
