# Generated by Django 2.2.4 on 2019-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0016_actividades_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=700, null=True),
        ),
    ]
