# Generated by Django 2.2.4 on 2019-10-02 15:24

import apps.direccion.models
import apps.direccion.validate_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0017_auto_20191001_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencias',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=apps.direccion.models.act_directory_path, validators=[apps.direccion.validate_file.validate_file_type]),
        ),
    ]
