# Generated by Django 2.2.4 on 2019-10-02 15:28

import apps.direccion.validate_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0018_auto_20191002_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencias',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[apps.direccion.validate_file.validate_file_type]),
        ),
    ]
