# Generated by Django 2.2.4 on 2019-10-02 15:33

import apps.direccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0019_auto_20191002_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencias',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=apps.direccion.models.act_directory_path),
        ),
    ]
