# Generated by Django 2.2.4 on 2019-10-04 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0020_auto_20191002_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos_Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
