# Generated by Django 2.2.4 on 2019-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0021_correos_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correos_notificacion',
            name='correo',
        ),
        migrations.AddField(
            model_name='correos_notificacion',
            name='correo_inst',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correos_notificacion',
            name='correo_per',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
