# Generated by Django 2.2.4 on 2019-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0025_actividades_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='see_panel',
            field=models.BooleanField(default=False),
        ),
    ]
