# Generated by Django 2.2.4 on 2020-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0026_permisos_see_panel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='evidencias',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
