# Generated by Django 2.2.4 on 2020-02-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0028_auto_20200110_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='delete_all',
            field=models.BooleanField(default=False),
        ),
    ]
