# Generated by Django 2.2.4 on 2020-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0030_actividades_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'ordering': ['prioridad', '-timestamp']},
        ),
        migrations.AddField(
            model_name='permisos',
            name='change_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='prioridad',
            field=models.SmallIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2),
        ),
    ]
