# Generated by Django 2.2.4 on 2020-04-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0031_auto_20200415_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='subdireccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdir', to='direccion.Direcciones'),
        ),
    ]
